<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- javascript a jquery -->
        <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
        <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
        <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
        <script src="pohledy/script.js"></script> 
    </head>
    <body>

        <!-- Výpis zpráv -->
        <?php if (isset($this->zpravy) && !empty($this->zpravy)): ?>
            <ul>
                <?php foreach ($this->zpravy as $zprava): ?>
                    <li><?php echo $zprava; ?></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>

        <h1><?php echo $konkretniAkce['nazev_akce'];?></h1>
        <!-- tlačítko pro přepínaní mezi vypisem a editem -->
        <?php if ($konkretniAkce["archivovano"] == 0): ?>
            <button id="switch">Switch</button>
        <?php endif; ?>

        <!-- Vypis akce -->
        <div id="vypis_a">
            <?php echo '<p>'.$konkretniAkce['popisek_akce'].'</p>';?>
            <h4>Datum zahajeni: </h4>
            <?php echo $konkretniAkce['datum_zahajeni']; ?>

            <!-- Delka dni -->   
            <h4>Datum konce: </h4>
            <?php echo $konkretniAkce['datum_konce']; ?>

            <!-- Misto konani -->
            <h4>Misto konani: </h4>
            <?php echo $konkretniAkce['misto_kon']; ?>

            <!-- Pořadatel -->
            <h4>Pořadatel</h4>
            <?php echo $konkretniAkce['poradatel']?>

            <div>
                <!-- Opakovannost -->
                <h4>Opakovannost</h4>
                <?php
                foreach ($this->data["opak"] as $opak){
                    if($konkretniAkce["id_opak"] == $opak["id_opak"]){
                        echo $opak["nazev_opak"];
                    }
                }
                ?>
            </div>

            <div>
                <!-- Kolo -->
                <h4>Kolo</h4>
                <?php
                foreach ($this->data["kolo"] as $kolo){
                    if($konkretniAkce["id_kolo"] == $kolo["id_kolo"]){
                        echo $kolo["nazev_kolo"];
                    }
                }
                ?>
            </div>

            <div>
                <!-- Disciplíny -->
                <h4>Disciplíny:</h4>
                <?php foreach ($this->data['akcedisc'] as $ad):
                    if($ad['id_akce'] == $konkretniAkce['id_akce']){
                        foreach ($this->data['disc'] as $disc): 
                            if($ad['id_disc'] == $disc['id_disc']){
                                    echo $disc['nazev_disc']."<br>";
                        }
                        endforeach;
                    }
                endforeach; ?>
            </div>

            <?php if ($konkretniAkce["archivovano"] == 1){ ?>
                <div>
                    <!-- Přítomní učitelé -->
                    <h4>Přítomní učitelé: </h4>
                    <?php
                    echo(($konkretniAkce['pritomni_uc']== '') ? ("<p>Nebyl zadán přítomný učitel</p>") : ("<p>".$konkretniAkce['pritomni_uc']."</p>")); 
                    ?>

                    <!-- Shrnutí akce -->
                    <h4>Shrnutí akce</h4>
                    <?php 
                    echo(($konkretniAkce['shrnuti']== '') ? ("<p>Shnrutí není k dispozici</p>") : ("<p>".$konkretniAkce['shrnuti']."</p>")); 
                    ?>

                    <!-- vypis jednotlivých soupisek -->
                    <div>
                        <h3>Soupisky:</h3>
                        <?php
                        foreach ($this->data["soup"] as $soup) {
                            ?>
                            <div>
                            <?php
                            if ($this->data['ia'] != $soup["id_akce"]) {
                                continue;
                            }
                            echo "<h4>".$soup['nazev_skupiny']."</h4>";
                            foreach ($this->data['ucastnici'] as $ucast) {
                                if (!($ucast['id_soup'] == $soup['id_soup'])) {
                                    continue;
                                }
                                foreach ($this->data['uzivatele'] as $uziv) {
                                    if (!($ucast['email'] == $uziv['email'])) {
                                        continue;
                                    }
                                    echo "<h5>".$uziv['jmeno']." ".$uziv['prijmeni']." ".$uziv['id_trid']."</h5>";                                    
                                    foreach ($this->data['du'] as $du) {
                                        if (!($du['id_ucast'] == $ucast['id_ucast'])) {
                                            continue;
                                        }
                                        ?>
                                        <div>
                                            <h6>Disciplíny:</h6>
                                            <?php
                                            foreach ($this->data['disc'] as $disc) {
                                                if (!($du['id_disc'] == $disc['id_disc'])) {
                                                    continue;
                                                }
                                                echo $disc['nazev_disc']."<br>";
                                            }
                                            ?>
                                        </div>
                                        <?php
                                    }
                                echo "<h6>Výsledek žáka:</h6> <p>".$ucast['vys_u']."</p>";
                                }
                            }
                            ?>
                            </div>
                            <?php
                        }
                        ?>
                    </div>
                    <form method="post">
                        <button type="submit" name="cele_smazat">Smazat</button>
                    </form>
                </div>
            <?php
            }
            ?>

            <!-- Přidání a vypis soupisek-->
            <div>
                <?php if ($konkretniAkce["archivovano"] == 0): ?>
                    <div>
                        <a href="vytvorsoupisku?ia=<?php echo $konkretniAkce['id_akce']; ?>"><button type="button">+</button></a>
                        <h2>Soupisky</h2>
                        <ul>
                            <?php foreach ($this->data["soup"] as $soup): ?>
                                <?php if($soup['id_akce']==$konkretniAkce['id_akce']){ ?>
                                    <li>
                                        <a href="soupiska?is=<?php echo $soup['id_soup']; ?>"><?= $soup['nazev_skupiny'];?></a>
                                    </li>
                                <?php }?>    
                            <?php endforeach; ?>
                        </ul>
                    </div>
                <?php endif; ?>
            </div>
        </div>

        <a href="archiv?iar=<?php echo $konkretniAkce['id_akce']; ?>">

            <?php if ($konkretniAkce["archivovano"] == 0): ?>
                <button type="button">Archivovat</button>
            <?php endif; ?>
        </a>

        <!-- ------------------------------------------------SWITCH---------------------------------------------------------------- -->

        <!-- Edit -->
        <div id="edit_a">

            <h2>Edit akce</h2>
            <form method="post">

    <!-- Edit akce-->     
                <div>
                    <h2>Akce</h2>
                    <!-- Nazev akce -->
                    <label for="nazev_akce">Nazev: </label>
                    <input type="text" name="nazev_akce" value="<?php echo $konkretniAkce['nazev_akce']; ?>">
                    <!-- Datum -->
                    <label for="datum_zahajeni">Datum zahajeni: </label>
                    <input type="date" name="datum_zahajeni" value="<?php echo $konkretniAkce['datum_zahajeni']; ?>">
                    <!-- Delka dni -->   
                    <label for="datum_konce">Delka dni: </label>
                    <input type="date" name="datum_konce" value="<?php echo $konkretniAkce['datum_konce']; ?>">
                    <!-- Misto konani -->
                    <label for="misto_kon">Misto konani: </label>
                    <input type="text" name="misto_kon" value="<?php echo $konkretniAkce['misto_kon']; ?>">
                    <!-- Poradatel -->
                    <label for="poradatel">Poradatel: </label>
                    <input  type="text" name="poradatel" value="<?php echo $konkretniAkce['poradatel']; ?>">
                    <!-- Opakovanost -->
                    <label for="opak">Opakovanost: </label>
                    <select name="id_opak" class="select_opak" style="width: 100%">
                        <?php foreach ($this->data['opak'] as $opak): ?>
                            <option value="<?php echo $opak['id_opak']; ?>" >
                                <?php echo $opak['nazev_opak'] ?>
                            </option>
                        <?php endforeach; ?>
                    </select>

                <label for="kolo">Kolo: </label>
                <select name="id_kolo" class="select_kolo" style="width: 100%">
                    <?php foreach ($this->data['kolo'] as $kolo): ?>
                        <option value="<?php echo $kolo['id_kolo']; ?>" >
                            <?php echo $kolo['nazev_kolo'] ?>
                        </option>
                    <?php endforeach; ?>
                </select>
                    <!-- Popis akce -->
                    <label for="popisek_akce">Popis: </label>
                    <textarea name="popisek_akce" rows="4" cols="50"><?php echo $konkretniAkce['popisek_akce']; ?></textarea>
                    <!-- Učitelé -->
                    <label for="pritomni_uc">Přítomní učitelé </label>
                    <input type="text" name="pritomni_uc" value="<?php echo $konkretniAkce['pritomni_uc']; ?>">
                </div>

            <!-- Edit akcedisc -->
                <div>
                    <h2>Disciplíny</h2>
                <!-- Přidání disciplín -->
                    <div class="divAkceDisc">
                        <select name="pridat_id_disc[]" class="select_disc" style="width: 100%" multiple>
                            <?php foreach ($this->data['disc'] as $disc){
                                $skipDisc = false;
                                foreach ($this->data['akcedisc'] as $ad) {
                                    if ($ad['id_disc'] == $disc['id_disc'] && $ad['id_akce'] == $konkretniAkce['id_akce']) {
                                        $skipDisc = true;
                                        break;
                                    }
                                }
                                if (!$skipDisc) {
                                ?>
                                    <option value="<?php echo $disc['id_disc']; ?>"><?php echo $disc['nazev_disc']; ?></option>
                            <?php 
                                }
                            }
                            ?>
                        </select>
                    </div>

                <!-- Výběr Discipliny s checkboxy-->
                    <div>
                        <label for="cb_smazat">Tlačítko pro odebrání vybraných disciplín</label>
                        <button type="submit" name="cb_smazat">Odebrat</button>
                        <?php 
                            foreach ($this->data['akcedisc'] as $ad){
                                if($ad['id_akce'] != $konkretniAkce['id_akce']){
                                    continue;
                                }
                        ?>
                                <input type="checkbox" name="selected_disc[]" value="<?php echo $ad['id_akce_disc']; ?>">
                                    <?php foreach ($this->data['disc'] as $disc){
                                        if($ad['id_disc'] != $disc['id_disc']){
                                            continue;
                                            }
                                            echo $disc['nazev_disc'];
                                        }
                                }
                                        ?>
                    </div>                   
                </div>
                <!-- Tlačítka pro Uložení a Smazání -->
                <button type="submit" name="ulozit">Uložit</button>
                <label for="cele_smazat">Tlačítko pro smazání akce</label>
                <button type="submit" name="cele_smazat">Smazat</button>
            </form>
        </div>

    </body>
</html>