<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Content Switching</title>
</head>
<body>
    <h1>Přidání a Výpis všech akce_disc</h1>

    <!-- Výpis zpráv -->
    <?php if (isset($this->zpravy) && !empty($this->zpravy)): ?>
        <ul>
            <?php foreach ($this->zpravy as $zprava): ?>
                <li><?php echo $zprava; ?></li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>

    <div id="content1">
        <label for="nazev_akce">Nazev: </label>
        <input type="text" name="nazev_akce">
        <!-- Datum -->
        <label for="datum_zahajeni">Datum zahajeni: </label>
        <input type="date" name="datum_zahajeni">
        <!-- Delka dni -->   
        <label for="datum_konce">Datum konce: </label>
        <input type="date" name="datum_konce">
    </div>

    <div id="content2" style="display: none;">
    </div>

    <button id="switch">Switch</button>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    $(document).ready(function() {
        var content1 = $("#content1");
        var content2 = $("#content2");

        $("#switch").click(function() {
            if (content1.css("display") === "block") {
                content1.css("display", "none");
                content2.css("display", "block");
            } else {
                content1.css("display", "block");
                content2.css("display", "none");
            }
        });
    });
</script>

</body>
</html>
