<h1>Přidání a Výpis všech disciplín</h1>

<!-- Výpis zpráv -->
<?php if (isset($this->zpravy) && !empty($this->zpravy)): ?>
    <ul>
        <?php foreach ($this->zpravy as $zprava): ?>
            <li><?php echo $zprava; ?></li>
        <?php endforeach; ?>
    </ul>


<?php endif; ?>

<!-- Formulář pro přidání disciplíny -->
<form method="post">
    <label for="id_disc">ID disciplíny:</label>
    <input type="number" name="id_disc">
    
    <label for="id_sport">ID sportu:</label>
    <select name="id_sport">
        <?php foreach ($this->data['sporty'] as $sport): ?>
            <option value="<?php echo $sport['id_sport']; ?>">
                <?php echo $sport['nazev_sportu']; ?>
            </option>
        <?php endforeach; ?>
    </select>
    
    <label for="nazev_disc">Název Disciplíny:</label>
    <input type="text" name="nazev_disc" required>
    
    <button type="submit" name="pridej">Přidat disciplínu</button>
</form>



<!-- Výpis všech disciplíny -->

<?php if (isset($this->data['discipliny']) && !empty($this->data['discipliny'])): ?>
    <h2>Všechny disciplíny</h2>
    <ul>
    <?php foreach ($this->data['discipliny'] as $disc): ?>
            <li>ID: <?php echo $disc['id_disc']; ?>, <br> ID sportu: <?php echo $disc['id_sport']; ?> <br>Název: <?php echo $disc['nazev_disc']; ?>

            <form method="post">
            <input type="hidden" name="editovana_disciplina_id" value="<?php echo $disc['id_disc']; ?>">
            <input type="hidden" name="editovany_sport_id" value="<?php echo $disc['id_sport']; ?>">
            <label for="novy_nazev_discipliny">Nový název disciplíny:</label>
            <input type="text" name="novy_nazev_discipliny" >
            <button type="submit" name="ulozit">Uložit</button>
</form>
                <form method="post">
                    <input type="hidden" name="smazana_disciplina_id" value="<?php echo $disc['id_disc']; ?>">
                    <button type="submit" name="smazat">Smazat</button>
                </form>
            </li>
            <!-- Zde můžete přidat další informace o sportu, které chcete zobrazit -->
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <p>Nejsou k dispozici žádné disciplíny.</p>
<?php endif; ?>




