<h1>Přidaní pozic pro sportovce</h1>

<!-- Výpis zpráv -->
<?php if (isset($this->zpravy) && !empty($this->zpravy)): ?>
    <ul>
        <?php foreach ($this->zpravy as $zprava): ?>
            <li><?php echo $zprava; ?></li>
        <?php endforeach; ?>
    </ul>


<?php endif; ?>

<!-- Formulář pro přidání pozic -->
<form  method="post">
    <label for="id_poz">ID pozice:</label>
    <input type="number" name="id_poz" >
    <label for="nazev_poz">Název pozice:</label>
    <input type="text" name="nazev_poz" required>
    <button type="submit" name="pridej">Přidat pozici</button>
</form>



<!-- Výpis všech sportů -->

<?php if (isset($this->data['poz']) && !empty($this->data['poz'])): ?>
    <h2>Všechny sporty</h2>
    <ul>
    <?php foreach ($this->data['poz'] as $poz): ?>
            <li>ID: <?php echo $poz['id_poz']; ?>, Název: <?php echo $poz['nazev_poz']; ?>
            <form method="post">
            <input type="hidden" name="editovana_pozice_id" value="<?php echo $poz['id_poz']; ?>">
            <label for="novy_nazev_pozice">Nový název pozice:</label>
            <input type="text" name="novy_nazev_pozice" required>
            <button type="submit" name="ulozit">Uložit</button>
</form>
                <form method="post">
                    <input type="hidden" name="smazana_pozice_id" value="<?php echo $poz['id_poz']; ?>">
                    <button type="submit" name="smazat">Smazat</button>
                </form>
            </li>
            <!-- Zde můžete přidat další informace o sportu, které chcete zobrazit -->
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <p>Nejsou k dispozici žádné pozice.</p>
<?php endif; ?>