<h1>Registrace</h1>

<form method="post" action="">
        <label for="name">Jméno:</label>
        <input type="text" name="name" required><br>

        <label for="surname">Příjmení</label>
        <input type="text" name="surname" required><br>

        <label for="email">E-mail:</label>
        <input type="email" name="email" required><br>

        <label for="password">Heslo:</label>
        <input type="password" name="password" required><br>

        <input type="submit" value="Registrovat">
    </form>