<!DOCTYPE html>
<html lang="cs">
<head>
    <base href="/">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MP evidence sportovcu</title>
</head>
<body>
    <header>
        <div>MP evidence sportovcu</div>
        <?php if ($this->prihlasenyUzivatel) { ?>

            <?= $this->prihlasenyUzivatel["jmeno"] ?>
            <?= $this->prihlasenyUzivatel["prijmeni"] ?>
            <a href="odhlaseni">Odhlásit se</a>

        <?php } else { ?>

            <a href="login">Přihlásit se</a>
        
        <?php } ?>
    </header>
    <nav>
        <ul>
            <li><a href="uvod">Úvod</a></li>
            <h2>Pridavani do databaze</h2>
            <li><a href="disciplina">Disciplina</a></li>
            <li><a href="sporty">Sporty</a></li>
            <li><a href="chyba">Chyba</a></li>
            <li><a href="ucastnik">Účastník</a></li>
            <li><a href="pozice">Pozice</a></li>
            <li><a href="uroven">Uroven</a></li>
            <li><a href="discucast">disc_ucaas</a></li>
            <li><a href="soupiska">Soupiska</a></li>
            <li><a href="sportuje">Sportuje</a></li> 
        </ul>

        <ul>
            <h2>Importy</h2>
            <li><a href="importcsv">Import žáku do db</a></li>
            <li><a href="tridy">Třídy</a></li>
        </ul>
        <ul>
            <h2>Ostatni</h2>
            <li><a href="akce">Vytvoreni Akcí</a></li>
            <li><a href="pridelenidisciplin">Přidelení žáku k disciplínam</a></li>
        </ul>
        <ul>
            <h2>Vypisy</h2>
            <li><a href="uzivatel">Učitelé</a></li>
        </ul>

        <ul>
            <h2>Ldap</h2>
            <li><a href="ldap">ldap</a></li>
        </ul>

    <div class="zpravy">
        <?php foreach ($zpravy as $zprava) { ?>
            <div><?= $zprava ?></div>
        <?php } ?>
    </div>

    </nav>
    <?php
        $this->kontroler->vypisPohled();
    ?>
</body>


</html>