<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Soupiska</title>
    </head>
    <body>
        <h1><?php echo $konkretniAkce['nazev_akce'];?></h1>
        <p><?php echo $konkretniAkce['datum_zahajeni'];?><p>
        <h2><?php echo $konkretniSoup['nazev_skupiny'];?></h2>
        

        <button id="switch">Switch</button>
        

        <!-- Vypis -->
        <div id="vypis">
            <div>
                <label>Učastníci:</label>
                <?php
                foreach ($this->data['ucast'] as $ucast){
                    if(!($ucast['id_soup'] == $konkretniSoup['id_soup'] && $ucast['potrvzeni'] == 1)){
                        continue;
                    }
                    foreach ($this->data['uziv'] as $uziv){
                        if(!($ucast['email'] == $uziv['email'])){
                            continue;
                        }
                        echo "<div>";
                        echo $uziv['jmeno']." ".$uziv['prijmeni']." ".$uziv['id_trid']."<br>";
                        foreach($this->data['du'] as $du){
                            if(!($du['id_ucast']==$ucast['id_ucast'])){
                                continue;
                            }
                            foreach($this->data['disc'] as $disc){
                                if(!($du['id_disc']==$disc['id_disc'])){
                                    continue;
                                }
                                echo $disc['nazev_disc']."<br>";
                            }
                        }
                        echo "</div>";
                    }
                }
                ?>

<form method="post">
    <button type="submit" name="genPDF">VygenerujPDF</button>
</form>
            </div>


            <?php 
            use Mpdf\Mpdf;

            if (isset($_POST['genPDF'])){
                $content = '
                <div id="vypis">
                    <div>
                        <label>Učastníci:</label>';
                
                foreach ($this->data['ucast'] as $ucast) {
                if (!($ucast['id_soup'] == $konkretniSoup['id_soup'] && $ucast['potrvzeni'] == 1)) {
                    continue;
                }
                foreach ($this->data['uziv'] as $uziv) {
                    if (!($ucast['email'] == $uziv['email'])) {
                        continue;
                    }
                    $content .= '<div>';
                    $content .= $uziv['jmeno'] . ' ' . $uziv['prijmeni'] . ' ' . $uziv['id_trid'] . '<br>';
                    foreach ($this->data['du'] as $du) {
                        if (!($du['id_ucast'] == $ucast['id_ucast'])) {
                            continue;
                        }
                        foreach ($this->data['disc'] as $disc) {
                            if (!($du['id_disc'] == $disc['id_disc'])) {
                                continue;
                            }
                            $content .= $disc['nazev_disc'] . '<br>';
                        }
                    }
                    $content .= '</div>';
                }
                }
                
                $content .= '
                    </div>
                </div>';
                
                // Vytvoření nové instance Mpdf
                $mpdf = new Mpdf();
                
                // Přidání obsahu do PDF
                $mpdf->WriteHTML($content);
                
                // Vytvoření PDF souboru
                $pdfFileName = __DIR__ . '/../pdfs/soupiska_' .$konkretniAkce['nazev_akce']  .'_'.$konkretniSoup['nazev_skupiny'].'_'. date('dmY_Hi'). '.pdf';
                $mpdf->Output($pdfFileName, 'F');
                
                echo 'PDF vygenerováno';
                            
            }

        
            
            ?>



            <!-- Vypis x pending -->

            <div>
                <!-- požadavek -->
                <form method="post">
                    <div>
                        <lable for="disc_pending">Chci se přidat</lable>
                        <select name="disc_pending[]" class="disc" style="width: 100%" multiple>
                        <?php
                            foreach ($this->data['disc'] as $disc){
                                foreach($this->data['ad'] as $ad){
                                    if($disc['id_disc'] == $ad['id_disc'] && $ad['id_akce'] == $konkretniSoup['id_akce']){
                                    ?>
                                        <option value="<?php echo $disc['id_disc']; ?>"><?php echo $disc['nazev_disc']; ?></option>          
                                    <?php
                                    }
                                }
                            }
                            ?>
                        </select>
                    </div>
                    <button type="submit" name="pridat_pending">Přidat se</button>
                </form>
            </div>
            <div>
                <!-- vyhodnocení -->
                <div>
                    <form method="post">
                        
                        <?php
                        foreach ($this->data['ucast'] as $ucast){
                            if(!($ucast['id_soup'] == $konkretniSoup['id_soup'] && $ucast['potrvzeni'] == 0)){
                                continue;
                            }
                        ?>
                            <input type="checkbox" name="selected_pending[]" value="<?php echo $ucast['id_ucast']; ?>">
                        <?php
                            foreach ($this->data['uziv'] as $uziv){
                                if(!($ucast['email'] == $uziv['email'])){
                                    continue;
                                }
                                echo "<div>";
                                echo "<p>".$uziv['jmeno']." ".$uziv['prijmeni']." ".$uziv['id_trid']."</p>";
                                foreach($this->data['du'] as $du){
                                    if(!($du['id_ucast']==$ucast['id_ucast'])){
                                        continue;
                                    }
                                    foreach($this->data['disc'] as $disc){
                                        if(!($du['id_disc']==$disc['id_disc'])){
                                            continue;
                                        }
                                        echo "<p>".$disc['nazev_disc']."</p>";
                                    }
                                }
                                echo "</div>";
                            }
                        }
                        ?>
                        <button type="submit" name="prijmout_pending">prijmout</button>
                        <button type="submit" name="odmitnout_pending">odmitnout</button>
                    </form>
                </div>  
            </div>
        </div>


            
        <!-- Edit -->
        <div id="edit">
            <h2>Edit soupisky</h2>
            <form method="post">
    <!-- Edit akce-->     
                <div>
                    <h2>Soupiska</h2>
                    <!-- Nazev skupiny -->
                    <label for="nazev_skupiny">Nazev: </label>
                    <input type="text" name="nazev_skupiny" value="<?php echo $konkretniSoup['nazev_skupiny']; ?>">
                </div>

            <!-- Edit ucastnik -->
                <div>
                    <h2>Úcastníci</h2>
                    <div>
                    <!-- Přidání dalšího učastníka -->
                        <div>
                            <label for="pridat_ucast">Přidat  účastníka: </label>
                            <select name="pridat_ucast" class="uziv" style="width: 100%">
                                <?php foreach($this->data['uziv'] as $uziv){
                                    $skipUcast = false;
                                    foreach ($this->data['ucast'] as $ucast){
                                        if ($ucast['email'] == $uziv['email'] && $ucast['id_soup'] == $konkretniSoup['id_soup']) {
                                            $skipUcast = true;
                                            break;
                                        }   
                                    }
                                    if (!$skipUcast) {
                                        ?>
                                        <option value="<?= $uziv['email']; ?>"><?=$uziv['id_trid']." ".$uziv['jmeno']." ".$uziv['prijmeni'] ; ?></option>
                                   <?php  
                                    }
                                } 
                            ?>
                            </select>
                        </div>
                        <div>
                            <select name="disc_k_prirazeni[]" class="disc" style="width: 100%" multiple>
                            <?php
                                foreach ($this->data['disc'] as $disc){
                                    foreach($this->data['ad'] as $ad){
                                        if($disc['id_disc'] == $ad['id_disc'] && $ad['id_akce'] == $konkretniSoup['id_akce']){
                                        ?>
                                            <option value="<?php echo $disc['id_disc']; ?>"><?php echo $disc['nazev_disc']; ?></option>          
                                        <?php
                                        }
                                    }
                                }
                                ?>
                            </select>
                        </div>
                    </div>

                    <!-- Výběr Discipliny s checkboxy-->
                    <div>
                        <label for="cb_smazat">Pro smazání vybraných disciplín</label>
                        <button type="submit" name="cb_smazat">Smazat</button>
                        <?php
                        foreach ($this->data['ucast'] as $ucast){
                            if(!($ucast['id_soup'] == $konkretniSoup['id_soup'])){
                                continue;
                            }
                        ?>
                            <input type="checkbox" name="selected_ucast[]" value="<?php echo $ucast['id_ucast']; ?>">
                        <?php
                            foreach ($this->data['uziv'] as $uziv){
                                if(!($ucast['email'] == $uziv['email'])){
                                    continue;
                                }
                                echo "<div>";
                                echo "<p>".$uziv['jmeno']." ".$uziv['prijmeni']." ".$uziv['id_trid']."</p>";
                                foreach($this->data['du'] as $du){
                                    if(!($du['id_ucast']==$ucast['id_ucast'])){
                                        continue;
                                    }
                                    foreach($this->data['disc'] as $disc){
                                        if(!($du['id_disc']==$disc['id_disc'])){
                                            continue;
                                        }
                                        echo "<p>".$disc['nazev_disc']."</p>";
                                    }
                                }
                                echo "</div>";
                            }
                        }
                        ?>
                    </div>                   
                </div>
                <!-- Tlačítka pro Uložení a Smazání -->
                <button type="submit" name="ulozit">Uložit</button>
                <button type="submit" name="cele_smazat">Smazat</button>
            </form>
        </div>
        <!-- javascript a jquery -->
        <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
        <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
        <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

        <!-- javascript (Combobox) -->
        <script>    
            $(document).ready(function() {
                // Applynuti select2 na vypsané disciplíny
                $('.uziv').select2({
                    dropdownAutoWidth : true,
                    placeholder: "-- Výběr sportovce --"
                });

                $('.disc').select2({
                    dropdownAutoWidth : true,
                    placeholder: "-- Výběr disciplín --"
                });
            });
        </script>

        <!-- javascript (Switch) -->
        <script>
            $(document).ready(function() {
                var vypis = $("#vypis");
                var edit = $("#edit");
                edit.css("display", "none");

                $("#switch").click(function() {
                    if (vypis.css("display") === "block") {
                        vypis.css("display", "none");
                        edit.css("display", "block");
                    } else {
                        vypis.css("display", "block");
                        edit.css("display", "none");
                    }
                });
            });
        </script>
        
    </body>
</html>