<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Soupiska</title>
    </head>
    <body>
        <h1><?php echo $konkretniSoup['nazev_skupiny'];?></h1>

        <button id="switch">Switch</button> 

        <!-- Vypis -->
        <div id="vypis">
            <div>
                <label>Učastníci:</label>
                <?php
                foreach ($this->data['ucast'] as $ucast){
                    if(!($ucast['id_soup'] == $konkretniSoup['id_soup'])){
                        continue;
                    }
                    foreach ($this->data['uziv'] as $uziv){
                        if(!($ucast['id_uziv'] == $uziv['id_uziv'])){
                            continue;
                        }
                        echo "<div>";
                        echo $uziv['jmeno']." ".$uziv['prijmeni']." ".$uziv['id_trid']."<br>";
                        foreach($this->data['du'] as $du){
                            if(!($du['id_ucast']==$ucast['id_ucast'])){
                                continue;
                            }
                            foreach($this->data['disc'] as $disc){
                                if(!($du['id_disc']==$disc['id_disc'])){
                                    continue;
                                }
                                echo $disc['nazev_disc']."<br>";
                            }
                        }
                        echo "</div>";
                    }
                }
                ?>
            </div>
        </div>


            
        <!-- Edit -->
        <div id="edit">
            <h2>Edit soupisky</h2>
            <form method="post">
    <!-- Edit akce-->     
                <div>
                    <h2>Soupiska</h2>
                    <!-- Nazev skupiny -->
                    <label for="nazev_skupiny">Nazev: </label>
                    <input type="text" name="nazev_skupiny" value="<?php echo $konkretniSoup['nazev_skupiny']; ?>">
                </div>

            <!-- Edit ucastnik -->
                <div>
                    <h2>Úcastníci</h2>
                    <!-- Výběr Discipliny s checkboxy-->
                    <div>
                        <label for="cb_smazat">Pro smazání vybraných disciplín</label>
                        <button type="submit" name="cb_smazat">Smazat</button>
                        
                        <?php
                        foreach ($this->data['ucast'] as $ucast){
                            if(!($ucast['id_soup'] == $konkretniSoup['id_soup'])){
                                continue;
                            }
                        ?>
                            <input type="hidden" name="edit_id_[]" value="<?php echo $ad['id_akce_disc']; ?>">
                            <input type="checkbox" name="selected_disc[]" value="<?php echo $ad['id_akce_disc']; ?>">
                        <?php
                            foreach ($this->data['uziv'] as $uziv){
                                if(!($ucast['id_uziv'] == $uziv['id_uziv'])){
                                    continue;
                                }
                                echo "<div>";
                                echo $uziv['jmeno']." ".$uziv['prijmeni']." ".$uziv['id_trid']."<br>";
                                foreach($this->data['du'] as $du){
                                    if(!($du['id_ucast']==$ucast['id_ucast'])){
                                        continue;
                                    }
                                    foreach($this->data['disc'] as $disc){
                                        if(!($du['id_disc']==$disc['id_disc'])){
                                            continue;
                                        }
                                        echo $disc['nazev_disc']."<br>";
                                    }
                                }
                                echo "</div>";
                            }
                        }
                        ?>
                    </div>                   
                </div>

                <!-- Tlačítka pro Uložení a Smazání -->
                <button type="submit" name="ulozit">Uložit</button>
                <button type="submit" name="cele_smazat">Smazat</button>
            </form>
        </div>

        <!-- javascript a jquery -->
        <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
        <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
        <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

        <!-- javascript (Switch) -->
        <script>
            $(document).ready(function() {
                var vypis = $("#vypis");
                var edit = $("#edit");
                edit.css("display", "none");

                $("#switch").click(function() {
                    if (vypis.css("display") === "block") {
                        vypis.css("display", "none");
                        edit.css("display", "block");
                    } else {
                        vypis.css("display", "block");
                        edit.css("display", "none");
                    }
                });
            });
        </script>
        
    </body>
</html>