<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- javascript a jquery -->
        <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
        <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
        <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
        <script src="pohledy/script.js"></script> 
    </head>
    <body>


        <h1>Generování soupisky</h1>

        <!-- Výpis zpráv -->
        <?php if (isset($this->zpravy) && !empty($this->zpravy)): ?>
            <ul>
                <?php foreach ($this->zpravy as $zprava): ?>
                    <li><?php echo $zprava; ?></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>

        <div id="soupiskaUcastnik">
            <!-- Formulář pro přidání soupisek -->
            <form  method="post">
                <!--sekce tabulky "soupiska"-->
                <h1><?php echo $konkretniakce['nazev_akce']; ?> </h1>
                <label for="nazev_soupisky">Název soupisky:</label>
                <input required type="text" name="nazev_soupisky" >
                <!--sekce tabulky "ucastnik"-->
                <h2>Účastník </h2>
                <div>
                    <select required name="email[]" class="select_uziv" style="width: 100%" multiple>
                        <?php foreach ($this->data['uziv'] as $uziv):?>
                            <option value="<?= $uziv['email']; ?>"><?= $uziv['id_trid']." ".$uziv['jmeno']." ".$uziv['prijmeni'] ; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <button type="submit" name="pridejSoupiskaUcastnik">Přidat záznam</button>
            </form>
        </div>

        <div id="disciplina">
            <form method="post">
                <h2>Přiřazení disciplíny</h2>
                <div>
                    <?php
                    foreach ($this->data['ucast'] as $ucast){
                        if(!($soupiska['id_soup']==$ucast['id_soup'])) {
                            continue;
                        }
                        foreach ($this->data['uziv'] as $uziv){
                            if(!($uziv['email'] == $ucast['email'])) {
                                continue;  
                            }
                            ?>
                            <input type="hidden" name="id_ucastnika[]" value="<?= $ucast['id_ucast'] ?>"> 
                            <label><?php echo $uziv['id_trid']." ".$uziv['jmeno']." ".$uziv['prijmeni'];?> </label>
                            <select name="ucastnici[<?= $ucast['id_ucast'] ?>][]" class="select_disc" style="width: 100%" multiple><?php
                                foreach ($this->data['disc'] as $disc){
                                    foreach($this->data['ad'] as $ad){
                                        if($disc['id_disc'] == $ad['id_disc'] && $ad['id_akce'] == $konkretniakce['id_akce']){?>
                                            <option value="<?php echo $disc['id_disc']; ?>"><?php echo $disc['nazev_disc']; ?></option>
                                        <?php
                                        }
                                    }
                                }
                                ?>
                            </select><br>
                        <?php
                        }
                    }
                    ?>
                </div>
                <button type="submit" name="priradDiscipliny">Uložit</button>
            </form>
        </div>

         <!-- javascript (phases/fáze) -->
         <script>
            $(document).ready(function() {
                var su = $("#soupiskaUcastnik");
                var d = $("#disciplina");


                    if (<?php echo intval($faze)?> == 0) {
                        su.css("display", "block");
                        d.css("display", "none");
                    } else {
                        su.css("display", "none");
                        d.css("display", "block");
                    }

            });
        </script>

    </body>
</html>
